version: 2
updates:
  - package-ecosystem: maven
    directory: /web-console
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-starter-parent
        update-types:
          - version-update:semver-major
      - dependency-name: org.springframework.ai:spring-ai-bom
        update-types:
          - version-update:semver-major
      - dependency-name: com.github.eirslett:frontend-maven-plugin
        update-types:
          - version-update:semver-major
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /web-console/frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: eclipse-temurin
        update-types:
          - version-update:semver-major
      - dependency-name: maven
        update-types:
          - version-update:semver-major
      - dependency-name: python
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
