apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-infra-rca-platform.backendName" . }}
  labels:
    {{- include "cluster-infra-rca-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
  selector:
    {{- include "cluster-infra-rca-platform.backendSelectorLabels" . | nindent 4 }}
