{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-infra-rca-platform.databaseSecretName" . }}
  labels:
    {{- include "cluster-infra-rca-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  database: {{ .Values.database.auth.database | quote }}
  username: {{ .Values.database.auth.username | quote }}
  password: {{ .Values.database.auth.password | quote }}
  root-password: {{ .Values.database.auth.rootPassword | quote }}
{{- end }}
