{{- if .Values.ingress.webConsole.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cluster-infra-rca-platform.webConsoleName" . }}
  labels:
    {{- include "cluster-infra-rca-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-console
  {{- with .Values.ingress.webConsole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.webConsole.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.webConsole.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.webConsole.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "cluster-infra-rca-platform.webConsoleName" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
