// @ts-nocheck

export const STORAGE_KEYS = {
  locale: "rca_console_language",
};

export const NAV_ITEMS = [
  { id: "overview", label: "Overview", icon: "speedometer2" },
  { id: "clusters", label: "Clusters", icon: "hdd-network" },
  { id: "reports", label: "RCA Reports", icon: "clipboard2-pulse" },
  { id: "incidents", label: "Incidents", icon: "exclamation-diamond" },
  { id: "pipeline", label: "Pipeline", icon: "diagram-3" },
  { id: "audit", label: "Audit", icon: "journal-check", roles: ["admin", "auditor"] },
  { id: "webhooks", label: "Webhooks", icon: "broadcast-pin" },
  { id: "settings", label: "Settings", icon: "gear" },
];

export const KO = {
  Overview: "개요",
  Clusters: "클러스터",
  "RCA Reports": "RCA 보고서",
  Incidents: "인시던트",
  Pipeline: "파이프라인",
  Audit: "감사로그",
  Webhooks: "웹훅",
  Settings: "설정",
  "Cluster Infra RCA": "클러스터 인프라 RCA",
  "Linux and Kubernetes infrastructure root cause console": "Linux 및 Kubernetes 인프라 원인 분석 콘솔",
  "Sign in": "로그인",
  Username: "계정",
  Password: "비밀번호",
  "Initial account": "초기 계정",
  "Invalid username or password": "계정 또는 비밀번호가 올바르지 않습니다",
  Logout: "로그아웃",
  Refresh: "새로고침",
  "Open incidents": "진행 중 인시던트",
  "RCA reports": "RCA 보고서",
  "Registered clusters": "등록 클러스터",
  "Healthy agents": "정상 에이전트",
  "Agent fleet": "에이전트 상태",
  "Analysis pipeline": "분석 파이프라인",
  "Policy queue": "정책 큐",
  "Policy blocked": "정책 차단",
  "APM Failure Surface": "APM 장애 표면",
  "Failure propagation": "장애 전파",
  "Signal stream": "시그널 스트림",
  "Cluster topology": "클러스터 토폴로지",
  "Recent RCA": "최근 RCA",
  "No reports loaded.": "불러온 보고서가 없습니다.",
  "No incidents loaded.": "불러온 인시던트가 없습니다.",
  "No clusters registered.": "등록된 클러스터가 없습니다.",
  "No audit events loaded.": "감사 이벤트가 없습니다.",
  "No action requests.": "조치 요청이 없습니다.",
  "No agents registered.": "등록된 에이전트가 없습니다.",
  "Create cluster": "클러스터 생성",
  "Cluster name": "클러스터 이름",
  Environment: "환경",
  Description: "설명",
  "Backend URL": "백엔드 URL",
  "Generate install command": "설치 명령 생성",
  "Install command": "설치 명령",
  Copy: "복사",
  "Copied.": "복사했습니다.",
  Delete: "삭제",
  "Delete cluster": "클러스터 삭제",
  "Type the cluster name to confirm deletion.": "삭제하려면 클러스터 이름을 입력하세요.",
  Cancel: "취소",
  Confirm: "확인",
  "Manual collection": "수동 수집",
  "Collect evidence": "증거 수집",
  Agents: "에이전트",
  Evidence: "증거",
  Topology: "토폴로지",
  Status: "상태",
  Node: "노드",
  Version: "버전",
  "Last heartbeat": "마지막 하트비트",
  "Risk reason": "위험 사유",
  "Alert name": "알림명",
  "Created at": "생성일",
  "Completed at": "완료일",
  "Report detail": "보고서 상세",
  "Root cause candidates": "원인 후보",
  "Evidence summary": "근거 요약",
  "Rule signals": "Rule 신호",
  "Rule evidence": "Rule 근거",
  "Matched fields": "매칭 필드",
  "Observed": "관측값",
  "Threshold": "임계값",
  "Next step": "다음 확인",
  "Supporting evidence": "지원 근거",
  "Evidence paths": "근거 경로",
  "No derived rule signals.": "파생된 Rule 신호가 없습니다.",
  "Additional checks": "추가 확인 명령",
  "Recommended actions": "권장 조치",
  "Policy gate": "정책 게이트",
  "Automation": "자동화",
  "Risk factors": "위험 사유",
  "Command preview": "명령 미리보기",
  "Request action": "조치 요청",
  "Approve": "승인",
  "Reject": "거절",
  "Complete manual": "수동 처리 완료",
  "Manual workflow": "수동 처리",
  "LLM diagnostic only": "LLM 진단 전용",
  "Rule based": "Rule 기반",
  "Automation blocked": "자동화 차단",
  "Export report": "보고서 내보내기",
  "Export all": "전체 내보내기",
  "Download bundle": "Evidence Bundle 다운로드",
  "Evidence bundle downloaded.": "Evidence Bundle을 다운로드했습니다.",
  "Signed bundle": "서명된 Bundle",
  "Unsigned bundle": "서명 없는 Bundle",
  "Bundle verification": "Bundle 검증",
  "Manifest summary": "Manifest 요약",
  "Offline verify": "오프라인 검증",
  "Copy verifier": "검증 명령 복사",
  "Bundle file": "Bundle 파일",
  "Entry count": "Entry 수",
  "ZIP size": "ZIP 크기",
  "Raw payload": "원본 Payload",
  "Entry hashes": "Entry 해시",
  "Last generated": "마지막 생성",
  "Quick filters": "빠른 필터",
  "All events": "전체 이벤트",
  "Export events": "Export 이벤트",
  "Auth failures": "인증 실패",
  "Approvals": "승인",
  "Selected audit event": "선택한 감사 이벤트",
  "Request context": "요청 컨텍스트",
  "No audit event selected.": "선택한 감사 이벤트가 없습니다.",
  "Cascading timeline": "장애 전파 타임라인",
  "Action requests": "조치 요청",
  "Analysis tasks": "분석 작업",
  "Demo scenarios": "데모 시나리오",
  Run: "실행",
  Retry: "재시도",
  "Alertmanager endpoint": "Alertmanager 엔드포인트",
  "Receiver sample": "Receiver 예시",
  "Audit search": "감사 검색",
  Search: "검색",
  Export: "내보내기",
  Open: "열기",
  "Client IP": "클라이언트 IP",
  Actor: "행위자",
  Event: "이벤트",
  Resource: "리소스",
  Outcome: "결과",
  Details: "상세",
  Language: "언어",
  English: "영어",
  Korean: "한국어",
  "Default admin account is active": "기본 관리자 계정이 활성화되어 있습니다",
  "Change the login ID and password after the first sign-in.": "최초 로그인 후 로그인 ID와 비밀번호를 변경하세요.",
  "Change login ID": "로그인 ID 변경",
  "Current login ID": "현재 로그인 ID",
  "New login ID": "새 로그인 ID",
  "Login ID changed.": "로그인 ID가 변경되었습니다.",
  "Change password": "비밀번호 변경",
  "Current password": "현재 비밀번호",
  "New password": "새 비밀번호",
  "Password changed.": "비밀번호가 변경되었습니다.",
  Save: "저장",
  "Console diagnostics": "콘솔 진단",
  "Run layout check": "레이아웃 검사",
  "Viewport": "뷰포트",
  "Page overflow": "페이지 넘침",
  "Offscreen elements": "화면 밖 요소",
  "Overflow candidates": "넘침 후보",
  "Clipped text candidates": "잘림 후보",
  "Last checked": "마지막 검사",
  "No layout issues detected.": "레이아웃 문제를 찾지 못했습니다.",
  Yes: "예",
  No: "아니오",
  "Platform info": "플랫폼 정보",
  "Platform version": "플랫폼 버전",
  "API version": "API 버전",
  "Agent protocol": "Agent 프로토콜",
  "Minimum agent protocol": "최소 Agent 프로토콜",
  "Minimum agent version": "최소 Agent 버전",
  "Export security": "Export 보안",
  "Max bundle size": "Bundle 최대 크기",
  "Hash algorithm": "Hash 알고리즘",
  "Bundle signature": "Bundle 서명",
  "Signature algorithm": "서명 알고리즘",
  "Signature key": "서명 키",
  Signature: "서명",
  "Offline verifier": "오프라인 검증기",
  Enabled: "활성화",
  Disabled: "비활성화",
  open: "진행 중",
  resolved: "해결됨",
  high: "높음",
  medium: "중간",
  low: "낮음",
  critical: "심각",
  warning: "경고",
  info: "정보",
  healthy: "정상",
  degraded: "저하",
  offline: "오프라인",
  stale: "지연",
  registered: "등록됨",
  active: "활성",
  agent_pending: "에이전트 대기",
  completed: "완료",
  failed: "실패",
  queued: "대기",
  processing: "처리 중",
  retry_wait: "재시도 대기",
  dead_letter: "실패 보관",
  pending_approval: "승인 대기",
  approved_manual: "수동 승인",
  rejected: "거절됨",
  blocked: "차단됨",
  accepted: "접수됨",
  AUTO_SAFE: "자동 안전",
  APPROVAL_REQUIRED: "승인 필요",
  GITOPS_PR_ONLY: "GitOps PR 전용",
  NEVER_AUTO_EXECUTE: "자동 실행 금지",
  MANUAL_INVESTIGATION: "수동 조사",
};

export const POLICY_HELP = {
  AUTO_SAFE: "Read-only evidence collection can be requested from the agent.",
  APPROVAL_REQUIRED: "A human approval record is required. Execution remains manual.",
  GITOPS_PR_ONLY: "Use a GitOps PR or runbook. Do not execute directly from the console.",
  NEVER_AUTO_EXECUTE: "High-risk remediation. The console only records review decisions.",
  MANUAL_INVESTIGATION: "Operator investigation is required before any remediation.",
};

export const SIGNAL_STAGES = [
  { key: "disk", label: "Disk I/O", icon: "nvme" },
  { key: "runtime", label: "Runtime", icon: "boxes" },
  { key: "kubelet", label: "Kubelet", icon: "cpu" },
  { key: "network", label: "Network", icon: "ethernet" },
  { key: "control", label: "Control Plane", icon: "diagram-2" },
  { key: "service", label: "Service Impact", icon: "activity" },
];
