export type Locale = "en" | "ko";

export interface NavItem {
  id: string;
  label: string;
  icon: string;
  roles?: readonly string[];
}

export const STORAGE_KEYS: Record<string, string> = {
  locale: "rca_console_language",
};

export const NAV_ITEMS: readonly NavItem[] = [
  { id: "overview", label: "Overview", icon: "speedometer2" },
  { id: "clusters", label: "Clusters", icon: "hdd-network" },
  { id: "reports", label: "RCA Reports", icon: "clipboard2-pulse" },
  { id: "incidents", label: "Incidents", icon: "exclamation-diamond" },
  { id: "pipeline", label: "Pipeline", icon: "diagram-3" },
  { id: "audit", label: "Audit", icon: "journal-check", roles: ["admin", "auditor"] },
  { id: "webhooks", label: "Webhooks", icon: "broadcast-pin" },
  { id: "settings", label: "Settings", icon: "gear" },
];

export const KO: Record<string, string> = {
  Overview: "개요",
  Clusters: "클러스터",
  "RCA Reports": "RCA 보고서",
  Incidents: "인시던트",
  Pipeline: "파이프라인",
  Audit: "감사로그",
  Webhooks: "웹훅",
  Settings: "설정",
  "Cluster RCA Console": "클러스터 RCA 콘솔",
  "Linux and Kubernetes infrastructure root cause console": "Linux 및 Kubernetes 인프라 원인 분석 콘솔",
  "Sign in": "로그인",
  Username: "계정",
  Password: "비밀번호",
  "Initial account": "초기 계정",
  "Invalid username or password": "계정 또는 비밀번호가 올바르지 않습니다.",
  Logout: "로그아웃",
  Refresh: "새로고침",
  "Signed in.": "로그인했습니다.",
  "Failed to load console data.": "콘솔 데이터를 불러오지 못했습니다.",
  "Failed to load report.": "보고서를 불러오지 못했습니다.",
  "Cluster created.": "클러스터를 생성했습니다.",
  "Cluster deleted.": "클러스터를 삭제했습니다.",
  "Agent token rotated.": "에이전트 토큰을 교체했습니다.",
  "Evidence collection requested.": "근거 수집을 요청했습니다.",
  "Action request updated.": "조치 요청을 갱신했습니다.",
  "Action request approved.": "조치 요청을 승인했습니다.",
  "Action request rejected.": "조치 요청을 거절했습니다.",
  "Manual handling completed.": "수동 처리를 완료했습니다.",
  "Incident resolved.": "인시던트를 해결 처리했습니다.",
  "Incident reopened.": "인시던트를 다시 열었습니다.",
  "Analysis task requeued.": "분석 작업을 다시 대기열에 넣었습니다.",
  "Demo scenario started.": "데모 시나리오를 시작했습니다.",
  "Export downloaded.": "Export 파일을 다운로드했습니다.",
  "Report exported.": "보고서를 내보냈습니다.",
  "Audit export downloaded.": "감사 로그 export 파일을 다운로드했습니다.",
  "Loading console": "콘솔을 불러오는 중",
  watch: "감시",
  "rule gate": "Rule 게이트",
  timeline: "타임라인",
  "Console navigation": "콘솔 메뉴",
  "Ops live": "운영 중",
  "Operations Console": "운영 콘솔",
  "APM Console": "APM 콘솔",
  "APM-style infrastructure lens": "APM 스타일 인프라 관측",
  "APM Failure Surface": "APM 장애 표면",
  "Node pressure, kernel/runtime evidence, control-plane latency, and policy-gated remediation in one operational surface.":
    "노드 압박, 커널/런타임 근거, 컨트롤 플레인 지연, 정책 기반 조치 흐름을 한 화면에서 봅니다.",
  "Open incidents": "진행 중 인시던트",
  "RCA reports": "RCA 보고서",
  "Registered clusters": "등록 클러스터",
  "Healthy agents": "정상 에이전트",
  "Agent fleet": "에이전트 상태",
  "Analysis pipeline": "분석 파이프라인",
  "Policy queue": "정책 큐",
  "Policy blocked": "정책 차단",
  "Operations readiness": "운영 준비 상태",
  "No agents": "에이전트 없음",
  "active tasks": "활성 작업",
  Queued: "대기",
  Processing: "처리 중",
  "approvals pending": "승인 대기",
  Manual: "수동",
  "Reports 24h": "24시간 보고서",
  signals: "시그널",
  "Failure propagation": "장애 전파",
  "Signal stream": "시그널 스트림",
  "Cluster topology": "클러스터 토폴로지",
  "Cluster detail sections": "클러스터 상세 섹션",
  "Recent RCA": "최근 RCA",
  "Evidence sequence by system layer": "시스템 계층별 근거 흐름",
  "Prioritized recent infrastructure signals": "우선순위가 높은 최근 인프라 시그널",
  "Registration and agent posture": "등록 상태와 에이전트 상태",
  "No report selected": "선택된 보고서 없음",
  "No reports loaded.": "불러온 보고서가 없습니다.",
  "No incidents loaded.": "불러온 인시던트가 없습니다.",
  "No clusters registered.": "등록된 클러스터가 없습니다.",
  "No audit events loaded.": "감사 이벤트가 없습니다.",
  "No action requests.": "조치 요청이 없습니다.",
  "No agents registered.": "등록된 에이전트가 없습니다.",
  "New node or control-plane evidence will appear here.": "새 노드 또는 컨트롤 플레인 근거가 여기에 표시됩니다.",
  "No evidence summary available.": "근거 요약이 없습니다.",
  Webhook: "웹훅",
  "Pipeline backlog": "파이프라인 대기열",
  "Create cluster": "클러스터 생성",
  "Cluster name": "클러스터 이름",
  Environment: "환경",
  Description: "설명",
  "Backend URL": "백엔드 URL",
  "Generate install command": "설치 명령 생성",
  "Install command": "설치 명령",
  "Register clusters, install node agents, and inspect collected evidence.":
    "클러스터를 등록하고 노드 에이전트 설치 명령과 수집 근거를 확인합니다.",
  "Minimal registration flow": "최소 등록 흐름",
  registered: "등록됨",
  Copy: "복사",
  "Copied.": "복사했습니다.",
  Delete: "삭제",
  "Delete cluster": "클러스터 삭제",
  "Type the cluster name to confirm deletion.": "삭제하려면 클러스터 이름을 입력하세요.",
  Cancel: "취소",
  Confirm: "확인",
  "Manual collection": "수동 수집",
  "Collect evidence": "근거 수집",
  Agents: "에이전트",
  Evidence: "근거",
  Topology: "토폴로지",
  Status: "상태",
  Node: "노드",
  Version: "버전",
  "Last heartbeat": "마지막 하트비트",
  "Risk reason": "위험 사유",
  "Alert name": "알림명",
  "Created at": "생성일",
  "Completed at": "완료일",
  "Node agent posture, evidence requests, and observed topology for this cluster.":
    "이 클러스터의 노드 에이전트 상태, 근거 요청, 관측된 토폴로지를 봅니다.",
  "No evidence requests.": "근거 요청이 없습니다.",
  "Topology observation is not loaded yet.": "토폴로지 관측 정보가 아직 없습니다.",
  "All registered agents are reporting healthy posture.": "등록된 모든 에이전트가 정상 상태를 보고 중입니다.",
  Stale: "지연",
  Degraded: "저하",
  Offline: "오프라인",
  "Report detail": "보고서 상세",
  "Root cause candidates": "원인 후보",
  "Evidence summary": "근거 요약",
  "Rule signals": "Rule 신호",
  "Rule evidence": "Rule 근거",
  "Matched fields": "매칭 필드",
  Observed: "관측값",
  Threshold: "임계값",
  "Next step": "다음 확인",
  "Supporting evidence": "지원 근거",
  "Evidence paths": "근거 경로",
  "No derived rule signals.": "파생된 Rule 신호가 없습니다.",
  "Additional checks": "추가 확인 명령",
  "Recommended actions": "권장 조치",
  "Policy gate": "정책 게이트",
  Automation: "자동화",
  "Risk factors": "위험 사유",
  "Command preview": "명령 미리보기",
  "Request action": "조치 요청",
  Approve: "승인",
  Reject: "거절",
  "Complete manual": "수동 처리 완료",
  "Manual workflow": "수동 처리",
  "LLM diagnostic only": "LLM 진단 전용",
  "Rule based": "Rule 기반",
  "Automation blocked": "자동화 차단",
  "Policy controlled workflow.": "정책으로 제어되는 워크플로입니다.",
  "Operator note": "운영자 메모",
  "Export report": "보고서 내보내기",
  "Export all": "전체 내보내기",
  "Download bundle": "Evidence Bundle 다운로드",
  "Evidence Bundle download": "Evidence Bundle 다운로드",
  "Evidence bundle downloaded.": "Evidence Bundle을 다운로드했습니다.",
  "Signed bundle": "서명된 Bundle",
  "Unsigned bundle": "서명 없는 Bundle",
  "Bundle verification": "Bundle 검증",
  "Manifest summary is available to export-authorized users after report detail loads.":
    "보고서 상세가 로드된 뒤 export 권한이 있는 사용자에게 manifest 요약이 표시됩니다.",
  "Report quality": "보고서 품질",
  "Rule signal sufficiency, freshness, collector coverage, and confidence gate":
    "Rule 신호 충분성, 신선도, collector 커버리지, 신뢰도 게이트",
  "Offline integrity check and current manifest preview": "오프라인 무결성 검증과 현재 manifest 미리보기",
  "Observed evidence order and inferred propagation": "관측 근거 순서와 추론된 전파 흐름",
  "Rule-based detector output before LLM analysis": "LLM 분석 전 Rule 기반 탐지 결과",
  "Ranked by rule and evidence confidence": "Rule 및 근거 신뢰도 기준 정렬",
  "Signals used by analyzer": "분석기에 사용된 시그널",
  "Commands to verify before remediation": "조치 전 확인할 명령",
  "Policy Engine result before any action request": "조치 요청 전 Policy Engine 결과",
  "Every action remains behind policy and human confirmation": "모든 조치는 정책과 사용자 확인 뒤에만 진행됩니다.",
  "Approval records and manual completion": "승인 기록과 수동 처리 완료",
  "No recommended actions.": "권장 조치가 없습니다.",
  "No root cause candidates.": "원인 후보가 없습니다.",
  "No evidence summary.": "근거 요약이 없습니다.",
  "No additional checks.": "추가 확인 명령이 없습니다.",
  "No policy decisions.": "정책 결정이 없습니다.",
  "Policy decision": "정책 결정",
  "Timeline evidence is not available.": "타임라인 근거가 없습니다.",
  "Root trigger": "최초 트리거",
  "Causal edges": "인과 관계",
  "Observed edges": "관측 순서",
  "Evidence quality": "근거 품질",
  "Root candidate score": "원인 후보 점수",
  "Selected timeline evidence": "선택된 타임라인 근거",
  "Observed at": "관측 시각",
  "Evidence type": "근거 유형",
  "Root score": "원인 점수",
  "Incoming relation": "유입 관계",
  "Quality gate": "품질 게이트",
  "Rule-based RCA is usable": "Rule 기반 RCA 사용 가능",
  "Additional evidence is required": "추가 근거 필요",
  "Report quality is not available for this report.": "이 보고서의 품질 정보가 없습니다.",
  "Quality status": "품질 상태",
  "Quality score": "품질 점수",
  "Confidence penalty": "신뢰도 패널티",
  "Agent health": "에이전트 상태",
  "Top score": "최고 점수",
  Penalty: "패널티",
  LLM: "LLM",
  "Diagnostic only": "진단 전용",
  Assistive: "보조",
  Freshness: "신선도",
  "Collected at": "수집 시각",
  "No collection timestamp": "수집 시각 없음",
  "Collector coverage": "Collector 커버리지",
  Missing: "누락",
  "Expected collectors reported": "예상 Collector가 보고되었습니다.",
  "Collector status": "Collector 상태",
  "No collector degradation reported": "Collector 저하가 보고되지 않았습니다.",
  "Agent detail": "에이전트 상세",
  "cluster scope": "클러스터 범위",
  "No heartbeat data": "하트비트 데이터 없음",
  "Audit search": "감사 검색",
  "Access, approval, export, agent auth, and administrative records.":
    "접근, 승인, export, 에이전트 인증, 관리 기록을 확인합니다.",
  "Filter by event, IP, actor, outcome, or text": "이벤트, IP, 행위자, 결과, 텍스트로 필터링",
  "Quick filters": "빠른 필터",
  "All events": "전체 이벤트",
  "Export events": "Export 이벤트",
  "Auth failures": "인증 실패",
  Approvals: "승인",
  "Selected audit event": "선택된 감사 이벤트",
  "Request context": "요청 컨텍스트",
  "No audit event selected.": "선택된 감사 이벤트가 없습니다.",
  Search: "검색",
  Export: "내보내기",
  Open: "열기",
  "Client IP": "클라이언트 IP",
  Actor: "행위자",
  Event: "이벤트",
  Resource: "리소스",
  Outcome: "결과",
  Details: "상세",
  events: "이벤트",
  "Correlated evidence grouped by node, cause, and recurrence.":
    "노드, 원인, 재발 기준으로 묶은 상관 근거입니다.",
  total: "전체",
  Resolve: "해결",
  Reopen: "다시 열기",
  "Root cause not available yet.": "아직 원인 정보가 없습니다.",
  "Analysis worker, approval queue, and built-in RCA scenario generator.":
    "분석 worker, 승인 큐, 내장 RCA 시나리오 생성기를 봅니다.",
  "Active tasks": "활성 작업",
  "Dead letter": "실패 보관",
  "Pending approvals": "승인 대기",
  "Blocked requests": "차단 요청",
  "Analysis tasks": "분석 작업",
  tasks: "작업",
  requests: "요청",
  "Demo scenarios": "데모 시나리오",
  "Generate realistic evidence without Prometheus": "Prometheus 없이 현실적인 근거 생성",
  "No analysis tasks.": "분석 작업이 없습니다.",
  "No demo scenarios.": "데모 시나리오가 없습니다.",
  "Auto demo cluster": "자동 데모 클러스터",
  "Select an RCA report.": "RCA 보고서를 선택하세요.",
  "Decision note": "결정 메모",
  Run: "실행",
  Retry: "재시도",
  "Alertmanager is optional; the backend can also request evidence collection directly.":
    "Alertmanager는 선택 사항이며, 백엔드가 직접 근거 수집을 요청할 수도 있습니다.",
  "Alertmanager endpoint": "Alertmanager 엔드포인트",
  "Protected by webhook token": "웹훅 토큰으로 보호됨",
  "Receiver sample": "Receiver 예시",
  Language: "언어",
  English: "영어",
  Korean: "한국어",
  "Console preferences and local admin credential rotation.": "콘솔 환경 설정과 로컬 관리자 계정 변경",
  "Preference is stored in this browser": "설정은 이 브라우저에 저장됩니다.",
  "Use this after the first default admin sign-in": "초기 관리자 로그인 후 사용하세요.",
  "Rotate the built-in admin password after install": "설치 후 내장 관리자 비밀번호를 변경하세요.",
  "Default admin account is active": "기본 관리자 계정이 활성화되어 있습니다.",
  "Change the login ID and password after the first sign-in.": "최초 로그인 후 로그인 ID와 비밀번호를 변경하세요.",
  "Change login ID": "로그인 ID 변경",
  "Current login ID": "현재 로그인 ID",
  "New login ID": "새 로그인 ID",
  "Login ID changed.": "로그인 ID가 변경되었습니다.",
  "Change password": "비밀번호 변경",
  "Current password": "현재 비밀번호",
  "New password": "새 비밀번호",
  "Password changed.": "비밀번호가 변경되었습니다.",
  Save: "저장",
  "Console diagnostics": "콘솔 진단",
  "Run a client-side layout check on the current console view": "현재 콘솔 화면의 레이아웃 깨짐을 브라우저에서 검사합니다.",
  "Run layout check": "레이아웃 검사",
  "Run a check to inspect the current viewport for overflow or clipped text.":
    "현재 화면의 넘침 또는 잘린 텍스트를 확인하려면 검사를 실행하세요.",
  Viewport: "뷰포트",
  "Page overflow": "페이지 넘침",
  "Offscreen elements": "화면 밖 요소",
  "Overflow candidates": "넘침 후보",
  "Clipped text candidates": "잘림 후보",
  "Last checked": "마지막 검사",
  "No layout issues detected.": "레이아웃 문제가 감지되지 않았습니다.",
  Yes: "예",
  No: "아니오",
  "Platform info": "플랫폼 정보",
  "Protocol compatibility and export integrity": "프로토콜 호환성과 export 무결성",
  "Platform version": "플랫폼 버전",
  "API version": "API 버전",
  "Agent protocol": "Agent 프로토콜",
  "Minimum agent protocol": "최소 Agent 프로토콜",
  "Minimum agent version": "최소 Agent 버전",
  "Export security": "Export 보안",
  "Max bundle size": "Bundle 최대 크기",
  "Hash algorithm": "Hash 알고리즘",
  "Bundle signature": "Bundle 서명",
  "Signature algorithm": "서명 알고리즘",
  "Signature key": "서명 키",
  Signature: "서명",
  "Offline verifier": "오프라인 검증기",
  Enabled: "활성화",
  Disabled: "비활성화",
  "LLM configuration": "LLM 설정",
  "Provider, model, and Secret wiring status": "Provider, model, Secret 연결 상태",
  "LLM secrets are read from environment variables or Kubernetes Secret. API keys are never rendered in the browser.":
    "LLM secret은 환경 변수 또는 Kubernetes Secret에서 읽습니다. API key 값은 브라우저에 표시하지 않습니다.",
  Provider: "Provider",
  Model: "Model",
  "Spring AI chat model": "Spring AI chat model",
  Credential: "Credential",
  "Credential env": "Credential env",
  "Base URL env": "Base URL env",
  "Provider default": "Provider 기본값",
  Configured: "설정됨",
  "Not required": "필요 없음",
  Timeout: "Timeout",
  Attempts: "시도 횟수",
  "Max output tokens": "최대 output token",
  "Circuit breaker": "Circuit breaker",
  "Test LLM": "LLM 테스트",
  "Run a live LLM connectivity test?": "실제 LLM 연결 테스트를 실행할까요?",
  "LLM test completed.": "LLM 테스트를 완료했습니다.",
  "LLM test skipped.": "LLM 테스트를 건너뛰었습니다.",
  "LLM test failed.": "LLM 테스트에 실패했습니다.",
  "LLM analyzer is disabled.": "LLM 분석기가 비활성화되어 있습니다.",
  "Spring AI chat model is not configured.": "Spring AI chat model이 설정되어 있지 않습니다.",
  "LLM provider returned a response.": "LLM provider가 응답했습니다.",
  "LLM provider test failed.": "LLM provider 테스트에 실패했습니다.",
  "LLM diagnostics": "LLM 진단",
  "Configuration checks": "설정 점검",
  "No LLM diagnostics loaded.": "LLM 진단 정보를 불러오지 않았습니다.",
  Remediation: "조치 안내",
  "Provider setup guide": "Provider 설정 가이드",
  "LLM setup guide": "LLM 설정 가이드",
  "No LLM setup guide loaded.": "LLM 설정 가이드를 불러오지 않았습니다.",
  "Use environment variables, Docker/Compose env files, Kubernetes Secret, or an external secret manager. The Web Console never stores or renders API key values.":
    "환경 변수, Docker/Compose env 파일, Kubernetes Secret 또는 외부 Secret Manager를 사용하세요. Web Console은 API key 값을 저장하거나 표시하지 않습니다.",
  "Use for OpenAI-hosted models through Spring AI OpenAI SDK.": "Spring AI OpenAI SDK를 통해 OpenAI 호스팅 모델을 사용할 때 선택합니다.",
  "Provider aliases: anthropic, claude.": "Provider alias: anthropic, claude.",
  "Provider aliases: gemini, google, google-genai.": "Provider alias: gemini, google, google-genai.",
  "Use a network-reachable Ollama endpoint. Base URL defaults depend on the runtime environment.":
    "Platform에서 접근 가능한 Ollama endpoint를 사용합니다. Base URL 기본값은 실행 환경에 따라 달라질 수 있습니다.",
  "Use for hosted gateways that implement the OpenAI-compatible API.":
    "OpenAI-compatible API를 구현한 외부 gateway를 사용할 때 선택합니다.",
  "Use only after the model endpoint is reachable from the Platform pod or process.":
    "Platform pod 또는 process에서 model endpoint에 접근 가능한 상태에서만 사용하세요.",
  "Base URL": "Base URL",
  Required: "필수",
  Optional: "선택",
  "Model examples": "Model 예시",
  "Notification delivery": "알림 전송",
  "Slack/SIEM delivery status and test controls": "Slack/SIEM 전송 상태와 테스트 제어",
  "Notification secrets are read from environment variables or Kubernetes Secret. Target URLs and tokens are never rendered in the browser.":
    "알림 Secret은 환경 변수 또는 Kubernetes Secret에서 읽습니다. 대상 URL과 토큰은 브라우저에 표시하지 않습니다.",
  "Test notification": "알림 테스트",
  "Send a test notification to configured delivery targets?": "설정된 전송 대상으로 테스트 알림을 보낼까요?",
  "Notification test delivered.": "테스트 알림을 전송했습니다.",
  "Notification test failed.": "테스트 알림 전송에 실패했습니다.",
  "Notification test skipped.": "테스트 알림 전송을 건너뛰었습니다.",
  "Slack webhook": "Slack Webhook",
  "Generic webhook": "Generic Webhook",
  "Bearer token": "Bearer 토큰",
  "Minimum severity": "최소 심각도",
  "Configured targets": "설정된 대상",
  "Delivery history": "전송 이력",
  "Recent notification delivery audit records": "최근 알림 전송 감사 기록",
  "Notification delivery history is visible to admin/auditor users.": "알림 전송 이력은 admin/auditor 사용자에게만 표시됩니다.",
  "No notification delivery history.": "알림 전송 이력이 없습니다.",
  Channel: "채널",
  "Status code": "상태 코드",
  skipped: "건너뜀",
  pass: "통과",
  fail: "실패",
  warn: "주의",
  ready: "준비됨",
  action_required: "조치 필요",
  restart_required: "재시작 필요",
  runtime_reload: "런타임 갱신",
  credential_required: "Credential 필요",
  no_api_key_required: "API key 불필요",
  open: "진행 중",
  resolved: "해결됨",
  high: "높음",
  medium: "중간",
  low: "낮음",
  critical: "심각",
  warning: "경고",
  info: "정보",
  healthy: "정상",
  degraded: "저하",
  offline: "오프라인",
  stale: "지연",
  active: "활성",
  agent_pending: "에이전트 대기",
  completed: "완료",
  failed: "실패",
  queued: "대기",
  processing: "처리 중",
  retry_wait: "재시도 대기",
  dead_letter: "실패 보관",
  pending_approval: "승인 대기",
  approved_manual: "수동 승인",
  rejected: "거절됨",
  blocked: "차단됨",
  accepted: "접수됨",
  partial: "부분 수집",
  limited: "제한됨",
  complete: "완료",
  not_registered: "미등록",
  unknown: "알 수 없음",
  AUTO_SAFE: "자동 안전",
  APPROVAL_REQUIRED: "승인 필요",
  GITOPS_PR_ONLY: "GitOps PR 전용",
  NEVER_AUTO_EXECUTE: "자동 실행 금지",
  MANUAL_INVESTIGATION: "수동 조사",
  "Read-only evidence collection can be requested from the agent.": "읽기 전용 근거 수집은 에이전트에 요청할 수 있습니다.",
  "A human approval record is required. Execution remains manual.": "사용자 승인 기록이 필요하며 실행은 수동 처리로 남습니다.",
  "Use a GitOps PR or runbook. Do not execute directly from the console.": "GitOps PR 또는 runbook을 사용하고 콘솔에서 직접 실행하지 않습니다.",
  "High-risk remediation. The console only records review decisions.": "고위험 조치입니다. 콘솔은 검토 결정만 기록합니다.",
  "Operator investigation is required before any remediation.": "조치 전에 운영자 조사가 필요합니다.",
  "Disk I/O": "디스크 I/O",
  Runtime: "런타임",
  Kubelet: "Kubelet",
  Network: "네트워크",
  "Control Plane": "컨트롤 플레인",
  "Service Impact": "서비스 영향",
  "Catalog override preview completed.": "카탈로그 override 미리보기를 완료했습니다.",
  "Catalog override preview rejected.": "카탈로그 override 미리보기가 거부되었습니다.",
  "Catalog override draft saved.": "카탈로그 override draft를 저장했습니다.",
  "Catalog override draft approved.": "카탈로그 override draft를 승인했습니다.",
  "Catalog override draft rejected.": "카탈로그 override draft를 거절했습니다.",
  "Catalog override draft discarded.": "카탈로그 override draft를 폐기했습니다.",
  "Override preview": "Override 미리보기",
  "Validate JSON and inspect catalog changes before deployment": "배포 전에 JSON과 카탈로그 변경 사항을 검증합니다.",
  "Override JSON": "Override JSON",
  Reason: "사유",
  "Change reason for audit": "감사로그에 남길 변경 사유",
  "Invalid JSON syntax.": "JSON 문법이 올바르지 않습니다.",
  "Preview override": "Override 미리보기",
  "Load sample": "샘플 불러오기",
  "Save this validated override as a review draft?": "검증된 override를 검토 draft로 저장할까요?",
  "Save draft": "Draft 저장",
  "Draft approval records review only. The console does not apply catalog changes.": "Draft 승인은 검토 기록만 남깁니다. 콘솔은 카탈로그 변경을 적용하지 않습니다.",
  "Override drafts": "Override draft",
  "Approved drafts are handed off to GitOps or a runbook.": "승인된 draft는 GitOps 또는 runbook으로 전달합니다.",
  "No override preview has been run yet.": "아직 override 미리보기를 실행하지 않았습니다.",
  "No catalog override drafts.": "카탈로그 override draft가 없습니다.",
  Valid: "유효",
  Discard: "폐기",
  "Requested by": "요청자",
  Created: "생성",
  "Reviewed by": "검토자",
  Reviewed: "검토",
  Diff: "Diff",
  "Show handoff": "Handoff 보기",
  "Use GitOps PR or a controlled runbook.": "GitOps PR 또는 통제된 runbook을 사용합니다.",
  "Pull request title": "Pull request 제목",
  "Pull request body": "Pull request 본문",
  "Proposed version": "제안 버전",
  "Proposed checksum": "제안 체크섬",
  "Change diff": "변경 diff",
  changes: "개 변경",
  truncated: "일부 생략",
  Current: "현재",
  Proposed: "제안",
  "No catalog changes detected.": "감지된 카탈로그 변경 사항이 없습니다.",
};

export const POLICY_HELP: Record<string, string> = {
  AUTO_SAFE: "Read-only evidence collection can be requested from the agent.",
  APPROVAL_REQUIRED: "A human approval record is required. Execution remains manual.",
  GITOPS_PR_ONLY: "Use a GitOps PR or runbook. Do not execute directly from the console.",
  NEVER_AUTO_EXECUTE: "High-risk remediation. The console only records review decisions.",
  MANUAL_INVESTIGATION: "Operator investigation is required before any remediation.",
};

export const SIGNAL_STAGES = [
  { key: "disk", label: "Disk I/O", icon: "nvme" },
  { key: "runtime", label: "Runtime", icon: "boxes" },
  { key: "kubelet", label: "Kubelet", icon: "cpu" },
  { key: "network", label: "Network", icon: "ethernet" },
  { key: "control", label: "Control Plane", icon: "diagram-2" },
  { key: "service", label: "Service Impact", icon: "activity" },
];
