{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "cluster-infra-rca-agent.namespace" . }}
  labels:
    {{- include "cluster-infra-rca-agent.labels" . | nindent 4 }}
{{- end }}
